### PR TITLE
Try 3 times if a get request times out before raising exception

### LINKED ISSUE #47: 504 GatewayTimeout returned while retrieving paged profiles
While using `connection.profiles.all` occasionally the namely API will return a 504 gateway timeout status while retrieving one of the pages. This raises an exception and derails the (sometimes lengthy) process of retrieving all of the paged results.

One possible solution would be to catch that exception and retry a few times before returning the error. PR example solution forthcoming...

### PR DESCRIPTION
**Pull request by rreinhardt9**
## Why

resolves #47

While using `connection.profiles.all` occasionally the namely API will return a 504 gateway timeout status while retrieving one of the pages. This raises an exception and derails the (sometimes lengthy) process of retrieving all of the paged results.

## What

This rescues the gateway timeout exception and retries 3 times before re raising it.

## Caveats

Right now this is just on the "get" request in the gem... but could be abstracted out and used for the other request types as well in the future (if needed)

This is a proof of concept... we may want to add it to the documentation if it's to be adopted?

### CODE REVIEW

**Comment by rreinhardt9** [comment]
Another thought on this if it goes forward... should we make the number of retries configurable? We could preserve the current functionality by making the default only 1 try.

**Comment by rreinhardt9** [comment]
expanding on the idea of abstracting the retries... we could have something like: 

```Ruby
    def with_retry
      retries ||= 0
      yield
    rescue RestClient::Exception => e
      raise unless [504].include?(e.http_code)
      retry if (retries += 1) < 3
      raise
    end

    def get(path, params = {})
      params.merge!(access_token: access_token)

      with_retry do
        JSON.parse(RestClient.get(url(path), accept: :json, params: params))
      end
    end
```

So that any of the requests could be wrapped in a `with_retry` block.

Additionally, the example above is experimenting with rescuing all RestClient exceptions, and then only retrying them based on their http_code. This might make it easier to add new types of failed requests to retry in the future... and could even be made configurable using an array of http codes to rescue.

File: lib/namely/resource_gateway.rb [hunk 1]
```diff
@@ -74,8 +74,13 @@ def extract_id(response)
     end
 
     def get(path, params = {})
+      retries ||= 0
       params.merge!(access_token: access_token)
       JSON.parse(RestClient.get(url(path), accept: :json, params: params))
+
+    rescue RestClient::GatewayTimeout
+      retry if (retries += 1) < 3
```
Comment (bobbytables) [inline lib/namely/resource_gateway.rb]: I'd really like for this to be a configurable value with the default being 0. Retries can be a slippery slope to making your own software slowdown as well. If for whatever reason Namely is down for the count, all requests to the API will not do 3 trys. Which could exacerbate the problem.

**Comment by bobbytables** [comment]
@rreinhardt9 - I've published 0.2.4 to RubyGems

**Comment by rreinhardt9** [comment]
@bobbytables that is so awesome! Thanks 🙌 ! And thanks for your team's work maintaining this open source lib :100:
